### ISSUE TITLE
SAL SHRD SHLD are missing

### ISSUE THREAD

**Issue by archercreat** [vtil-project/VTIL-NativeLifters#11]

**Comment by can1357** [comment]
Not sure how we forgot this, will be added whenever we get free time from the core.

**Comment by AltairQ** [comment]
SAL is equivalent to SHL, which is already implemented.

**Comment by archercreat** [comment]
> 
> 
> SAL is equivalent to SHL, which is already implemented.

It is, but there are no handler for X86_INS_SAL.

**Comment by AltairQ** [comment]
You're right, however they share the same opcodes and `amd64::disasm` seems to prefer decoding them as `shl`, so you'd have to really try to pass it to the lifter. Still, I guess it's better to handle all cases.
